Feature
Deepakdanger/hotelhouse_backend pull request #1
Opened 2021-12-19 15:19 UTC by Deepakdanger

This is the backend development of the In-Home website.
- Here I Have used the JWT token for authentication.
- Created model user, House, and Favourites.
- There is also validation and association of models.
- Here sending data in form of JSON to the frontend.
- Here we send only when the user is confirmed.

2021-12-22 03:04 UTC, rvvergara requested changes
Hi Deep, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

I notice we are not sanitizing user inputs in the controllers. let's do so.

Also let us make sure our controller action names and route names are restful

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-12-22 03:04 UTC, rvvergara commented on Gemfile
> +  gem 'pg', '~> 1.1'
Are we not also using postgres for development and test?

2021-12-22 03:04 UTC, rvvergara commented on app/controllers/authentication_controller.rb
> +  def authenticate
Let's keep our controller action names follow RESTful conventions. "authenticate" isn't a RESTful action name.

Only use any of the ff: Index, Show, Create, Update, Destroy

2021-12-22 03:04 UTC, rvvergara commented on app/controllers/favourites_controller.rb
> +    @fab = current_user.favourites.new(house_id: params[:house_id])
Don't you think we should be sanitizing our user inputs? Because as I see it this is a security vulnerability

2021-12-22 03:04 UTC, rvvergara commented on app/controllers/users_controller.rb
> +    @user = User.create(name: params[:name], email: params[:email], password: params[:password])
Ditto, we are not sanitizing user inputs here.

2021-12-22 03:04 UTC, rvvergara commented on config/database.yml
> +  password: Deepak@123
Kindly make sure we are not pushing credentials in the public repo.

2021-12-22 03:04 UTC, rvvergara commented on db/schema.rb
> +    t.string "email"
We should be enforcing uniqueness at the database level. Validating in the user model isn't enough.

2021-12-22 03:04 UTC, rvvergara commented on db/schema.rb
> +
We should also be enforcing foreign key constraints to keep data integrity

2021-12-22 03:04 UTC, rvvergara commented on config/routes.rb
> +  post 'authenticate', to: 'authentication#authenticate'
Let's make sure our route names are RESTful.

2021-12-27 08:16 UTC, rvvergara requested changes
Hi @Deepakdanger , 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Suggested changes
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-12-27 08:16 UTC, rvvergara commented on Gemfile
> +  gem 'pg', '~> 1.1'
I think we forgot to address this @Deepakdanger

2021-12-27 08:16 UTC, rvvergara commented on app/controllers/users_controller.rb
> +    @user = User.create(name: params[:name], email: params[:email], password: params[:password])
We haven't addressed this either @Deepakdanger

2021-12-27 09:29 UTC, rvvergara requested changes
Hi @Deepakdanger,

Let's pls make sure we address all the comments. To help me review please do reply to them and making sure that we've made the changes.

2021-12-27 09:29 UTC, rvvergara commented on config/routes.rb
> +  post 'authenticate', to: 'authentication#authenticate'
Let's please address this :) Forgot to remind you in my 2nd review

2021-12-27 09:29 UTC, rvvergara commented on app/controllers/authentication_controller.rb
> +  def authenticate
@Deepakdanger, having an "index" action for authentication doesn't make sense. When we use index it means we are returning a list of a resource.

In this particular case you are creating a "resource" called "authentication". What might be the most appropriate RESTful action name for this?

2021-12-27 10:11 UTC, Deepakdanger commented
Used POST method to create JWT Token when user wants to sign in.

2021-12-28 07:19 UTC, rvvergara commented on app/controllers/authentication_controller.rb
> +  def authenticate
All good!

2021-12-28 07:19 UTC, rvvergara commented on app/controllers/users_controller.rb
> +    @user = User.create(name: params[:name], email: params[:email], password: params[:password])
All good!

2021-12-28 07:19 UTC, rvvergara commented on config/database.yml
> +  password: Deepak@123
All good!

2021-12-28 07:19 UTC, rvvergara commented on db/schema.rb
> +    t.string "email"
All good!

2021-12-28 07:19 UTC, rvvergara commented on db/schema.rb
> +
All good!

2021-12-28 07:21 UTC, rvvergara commented on config/routes.rb
> +  post 'authenticate', to: 'authentication#authenticate'
Our routes still are not fully RESTful. While it's not a rule (more of a generally accepted convention) and I won't push it further, it's a high recommendation that we get used to using RESTful names for our routing. I suggest reading articles about REST and REST API's to master the principle

2021-12-28 07:22 UTC, rvvergara approved these changes
Hi @Deepakdanger , 

In my opinion, your backend is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-12-28 08:07 UTC, merged